apiVersion: v1
kind: Service
metadata:
  name: chroma-server
  namespace: chroma
  labels:
    app: chroma-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: chroma-server
